export const AUTHORIZATION = 'AUTHORIZATION';

export const MUTATE_USERINFO = 'MUTATE_USERINFO';

export const MUTATE_GYM_INFO_LIST = 'MUTATE_GYM_INFO_LIST';

export const ADD_GYM_INFO_LIST_SELECTED = 'ADD_GYM_INFO_LIST_SELECTED';
export const REMOVE_ITEM_FROM_GYM_INFO_LIST_SELECTED = 'REMOVE_ITEM_FROM_GYM_INFO_LIST_SELECTED';

export const MUTATE_COACH_INFO_LIST_SELECTED = 'MUTATE_COACH_INFO_LIST_SELECTED';
export const MUTATE_CLASS_INFO_LIST_SELECTED = 'MUTATE_CLASS_INFO_LIST_SELECTED';
export const MUTATE_CLASS_INFO_SELECTED = 'MUTATE_CLASS_INFO_SELECTED';

export const MUTATE_OSS_SESSION = 'MUTATE_OSS_SESSION';
export const MUTATE_GYM_ADMIN_INFO_SELECTED = 'MUTATE_GYM_ADMIN_INFO_SELECTED';
